name: linter-auto

on: [push]

jobs:
  start-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      
      - name: install 
        run: 
          npm ci

      - name: run tests
        run: 
          npm run test    